#!/usr/bin/env bash

# Change this depending on your battery in /sys/class/power_supply/
battery="BAT0";

has_battery() {
    if [ -d /sys/class/power_supply/$battery ]; then
        return 0;
    fi
    return 1;
}
get_battery_status() {
    icon="BAT"
    charge="$(get_charge)"
    echo ""$icon" "$charge"%"
}

get_charging_status() {
    charging_status=`cat "/sys/class/power_supply/$battery/status"`
    if [ $charging_status = "Discharging" ]; then
        echo ""
    else
        echo " "
    fi
}

get_charge() {
    cat "/sys/class/power_supply/$battery/capacity"
}

get_datetime() {
    date +"%a %d %b %Y │ %I:%M %p %Z"
}

get_mpd_status() {
    song="$(mpc current)"
    echo ""$song""
}


get_status() {
    battery_status="";
    if $(has_battery); then
        battery_status="$(get_battery_status) $(get_charging_status)│";
    fi
    mpd_status="$(get_mpd_status)";
    if [ ! -z "$mpd_status" ]; then
        mpd_status=" $mpd_status │";
    else
        mpd_status="";
    fi

    echo "${mpd_status} ${battery_status} $(get_datetime)";
}


while true
do
    xsetroot -name "$(get_status)";
    sleep 30s;
done
